name: 📅 Calendar
description: Getting help finding events, addings events, or anything else to do with the SCRF calendar.
title: "📅 - Calendar"
labels: [general]
assignees:
  - SirAh0
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new user form!

  - type: textarea
    id: text
    attributes:
      label: Issue Text
      description: text goes here!