name: 🗪 Chat Calendar 
description: A listed calendar event item has an error.
title: "🗪 - Calendar"
labels: [bug, chat]
assignees:
  - SirAh0
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new user form!

  - type: textarea
    id: text
    attributes:
      label: Issue Text
      description: text goes here!